sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install coverage
- pip install coveralls
- pip install pycodestyle
- cp travis-ci/manage.py manage.py
script:
- pycodestyle infohub/
- coverage run --source=infohub/ manage.py test infohub
after_success:
- coveralls
before_deploy:
- find infohub/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > infohub/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure:
  on:
    tags: true
    python: '3.6'
