version: '2'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: BLTI_DEV
      LTI_DEVELOP_APP: infohub
    restart: always
    container_name: app-infohub
    build:
      context: .
    volumes:
      - ./infohub:/app/infohub
    ports:
      - "8000:8000"

