version: '2'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      LTI_CONSUMERS: '{"0000-0000-0000": "01234567ABCDEF"}'
      BLTI_AES_KEY: "AE91AE1DF0E6FB44"
      BLTI_AES_IV: "01C8837249AE8667"
    restart: always
    container_name: app-infohub
    build:
      context: .
    volumes:
      - ./infohub:/app/infohub
    ports:
      - "8000:8000"

