autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
affinity:
   podsSpanNodes: true

ingress:
  enabled: true
  tls:
    myuw:
      secretName: infohub.canvas.uw.edu-ingress-cert
      hosts:
        - infohub.canvas.uw.edu
  hosts:
    myuw:
      host: infohub.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true

database:
  engine: null

repo: infohub
instance: prod

memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

environmentVariables:
  - name: CLUSTER_CNAME
    value: infohub.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: dev
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: LTI_CONFIG_DIRECTORY
    value: /lti/config

externalSecrets:
  enabled: true
  secrets:
    - name: infohub.canvas.uw.edu-secrets
      externalKey: infohub/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: infohub.canvas.uw.edu-lti-keys
      externalKey: infohub/prod/lti-keys
      data:
        - name: private-key-1.key
          property: private-key-1.key
        - name: public-key-1.key
          property: public-key-1.key

environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: infohub.canvas.uw.edu-secrets
    secretKey: django-secret
  infohubBLTICONSUMERS:
    name: LTI_CONSUMERS
    secretName: infohub.canvas.uw.edu-secrets
    secretKey: lti-consumers
  infohubBLTIAESKey:
    name: BLTI_AES_KEY
    secretName: infohub.canvas.uw.edu-secrets
    secretKey: blti-aes-key
  infohubBLTIAESIV:
    name: BLTI_AES_IV
    secretName: infohub.canvas.uw.edu-secrets
    secretKey: blti-aes-iv

mountedSecrets:
  enabled: true
  mountPath: /lti/keys
  secretName: infohub.canvas.uw.edu-lti-keys

podVolumes:
  lti-tool-config:
    volume:
      configMap:
        name: lti-tool-config
    mount:
      mountPath: /lti/config
    containers: [base]

configmaps:
  lti-tool-config:
    tool.json: |
      {
        "https://canvas.uw.edu": [{
          "default": true,
          "client_id": "100000000000811",
          "auth_login_url": "https://sso.canvaslms.com/api/lti/authorize_redirect",
          "auth_token_url": "https://sso.canvaslms.com/login/oauth2/token",
          "key_set_url": "https://sso.canvaslms.com/api/lti/security/jwks",
          "key_set": null,
          "private_key_file": "/lti/keys/private-key-1.key",
          "public_key_file": "/lti/keys/public-key-1.key",
          "deployment_ids": ["206138:82ea3323587ae330766ae046461fd35c747ed747"]
        }]
      }
